bai/urls.py
from django.urls import path
from .views import importCie10, DiagnosticoList, importRips, Grafdiagnosticoscie10, Home, \
DiagnosticoUpdate, DiagnosticoCreate, Archivocontrolist, Archivoconsultalist, ListadoDiagnostico, \
georrefenciarDiagCE, geolocMapaCalorDiagCE, mapaCalarDiagCE, listarRipsCargados

app_name='bai'


urlpatterns = [
	path('', Home.as_view(), name='home'),
	path('importcie10', importCie10, name='Import_cie10'),
	path('rips', importRips, name='importar_rips'),
	path('cie10/estcoom', Grafdiagnosticoscie10.as_view(), name='estadistica_cie10'),
	path('cie10', DiagnosticoList.as_view(), name='cie10list'),
	path('cie10/edit/<int:pk>', DiagnosticoUpdate.as_view(), name='cie10_edit'),
	path('cie10/new', DiagnosticoCreate.as_view(), name='cie10_new'),
	path('rips/ctrl', Archivocontrolist.as_view(), name='rips_control'),
	path('rips/listar/<int:id>', listarRipsCargados, name='rips_listar'),
	path('rips/ce', Archivoconsultalist.as_view(), name='rips_consulta'),
	path('rips/grce', ListadoDiagnostico.as_view(), name='georref_ce'),
	path('rips/grce/<int:iddiag>', georrefenciarDiagCE, name='georref_ce_map'),
	path('rips/grmcce/<int:iddiag>', geolocMapaCalorDiagCE, name='georref_mapcalor_ce'),
	path('rips/mapacalorce/<int:iddiag>', mapaCalarDiagCE, name='mapcalor_ce'),





]

cnf/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views


from .views import Home, HomeSinPrivilegio, PacienteView, PacienteCreate, PacienteEdit, inactivarPaciente, \
PacienteAjaxCreate, pacienteListView, load_barrios, listadopacientereload

app_name='cnf'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='cnf/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='cnf/login.html'), name='logout'),
    path('sin_privilegios/', HomeSinPrivilegio.as_view(), name='sin_privilegios'),
    path('paciente/', PacienteView.as_view(), name='paciente_list'),
    path('paciente/new', PacienteCreate.as_view(), name='paciente_new'),
    path('paciente/edit/<int:pk>', PacienteEdit.as_view(), name='paciente_edit'),
    path('paciente/estado/<int:id>', inactivarPaciente, name='paciente_inactivar'),
    path('paciente/new/ajax', PacienteAjaxCreate.as_view(), name='paciente_new_ajax'),
    path('paciente/list/', pacienteListView.as_view(), name='paciente_list_ajax'),
    path('ajax/load-barrio/', load_barrios, name='ajax_load_barrio'),
    path('pac/list/', listadopacientereload, name='list_paciente_reload'),

      

]

cvd/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
#from django.conf.urls import url
from cnf.views import Sin_privilegio
from django.views import generic

from .views import BacList, BacCreate, BacEdit, FichaIecList, FichaIecCreate, FichaIecEdit, \
AntecedenteViajeCreate, SeguimientoIecList, SeguimientoIecNew, SeguimientoIecedit, tareasSegIec, \
ConglomeradoList, ConglomeradoCreate, ConglomeradoEdit, geolocConglomerado, importarCovid19, \
notifCovidList, SeguimientoNotifCovid, anexos_fichaIec, AntecedenteViajeUpdate, \
AntecHospitalizacionCreate, AntecHospitalizacionUpdate, FileIecList, FileIecCreate, FileIecUpdate, \
ContactoIecCreate, ContactoIecUpdate, ContactoIecList, contactoIecDetail, DesplazaContactoCreate, \
DesplazaContactoUpdate, SeguimientoContactoCreate, SeguimientoContactoUpdate, GrafCovidSemEpi, \
inactivarNotifPaconglemerado, NotifPaConglomeradoList, NotifPaConglomeradoCreate, NotifPaConglomeradoUpdate, \
ContactoAisladoCreate, ContactoAisladoUpdate, SegContactoAisladoCreate, SegContactoAisladoUpdate, \
ConfigConglomeradoList, ConfigConglomeradoCreate, ConfigConglomeradoUpdate, GrafSintomasCovid, \
GrafCovidBarrio, GrafCoomorbCovid, geolocFichasIEC, PacienteCreate,createNewPac, busqpaciente, \
PrincipalCovid, notifCovidEdit, SeguimientoNotifCovidUpdate


from .reportes import imprimir_tareas_list, ReporteCuadroMando, ReportConglomerado, RepConglomerado

app_name='cvd'

urlpatterns = [

    path('', PrincipalCovid.as_view(), name='home'),
    path('baclist', BacList.as_view(), name='bac_list'),
    path('bac/new', BacCreate.as_view(), name='bac_new'),
    path('bac/edit/<int:pk>', BacEdit.as_view(), name='bac_edit'),
    path('iec', FichaIecList.as_view(), name='iec_list'),
    path('iec/new', FichaIecCreate.as_view(), name='iec_new'),
    path('iec/edit/<int:pk>', FichaIecEdit.as_view(), name='iec_edit'),
    path('iec/contacto/new/<int:idficha>',ContactoIecCreate.as_view(), name='contactoiec_new'),
    path('iec/contacto/edit/<int:pk>', ContactoIecUpdate.as_view(), name='contactoiec_edit'),
    path('iec/verfichaiec/<int:id>', anexos_fichaIec, name='ver_fichaiec'),
    path('iec/antviaje/new/<int:idficha>',AntecedenteViajeCreate.as_view(), name='iec_viaje_new'),
    path('iec/antviaje/edit/<int:pk>', AntecedenteViajeUpdate.as_view(), name='iec_viaje_edit'),
    path('iec/anthosp/new/<int:idficha>', AntecHospitalizacionCreate.as_view(), name='iec_anthosp_new'),
    path('iec/anthosp/edit/<int:pk>', AntecHospitalizacionUpdate.as_view(), name='iec_anthosp_edit'),
    path('iec/seg', SeguimientoIecList.as_view(), name='iec_seguimiento_list'),
    path('iec/seg/new', SeguimientoIecNew.as_view(), name='iec_seguimiento_new'),
    path('iec/seg/edit/<int:pk>', SeguimientoIecedit.as_view(), name='iec_seguimiento_edit'),
    path('iec/tareas', tareasSegIec, name='iec_tareas_list'),
    path('iec/imprimir-todas/<str:f1>/<str:f2>', imprimir_tareas_list, name='iec_tareas_print_all'),
    path('iec/conglomerado', ConglomeradoList.as_view(), name='conglomerado_list'),
    path('iec/conglomerado/new', ConglomeradoCreate.as_view(), name='conglomerado_new'),
    path('iec/conglomerado/edit/<int:pk>', ConglomeradoEdit.as_view(), name='conglomerado_edit'),
    path('iec/conglomerado/geoloc', geolocConglomerado, name='geoloc_conglomerado'),
    path('iec/fileiec', FileIecList.as_view(), name='fileiec_list'),
    path('iec/fileiec/new/<int:idficha>', FileIecCreate.as_view(), name='fileiec_new'),
    path('iec/fileiec/edit/<int:pk>', FileIecUpdate.as_view(), name='fileiec_edit'),
    path('iec/repcuadromando', ReporteCuadroMando.as_view(), name='cuadro_mando_rep'),
    path('iec/contacto', ContactoIecList.as_view(), name='contacto_list'),
    path('iec/contacto/detalle/<int:id>', contactoIecDetail, name='contacto_detalle'),        
    path('iec/contacto/desp/new/<int:id>', DesplazaContactoCreate.as_view(), name='desplacontacto_new'),        
    path('iec/contacto/desp/edit/<int:pk>', DesplazaContactoUpdate.as_view(), name='desplacontacto_edit'),        
    path('iec/contacto/seg/new/<int:id>', SeguimientoContactoCreate.as_view(), name='seguimientocontacto_new'),        
    path('iec/contacto/seg/edit/<int:pk>', SeguimientoContactoUpdate.as_view(), name='seguimientocontacto_edit'),        
    path('iec/graf/cvd/', GrafCovidSemEpi.as_view(), name='estadisticacovid_sem'),      
    path('import/sivigila', importarCovid19, name='import_covid'),
    path('sivcovid/list', notifCovidList, name='notif_covid_sivigila_list'),
    path('sivcovid/ver/<int:id>', notifCovidEdit, name='notif_covid_sivigila_ver'),
    path('sivcovid/seg/<int:idnotif>', SeguimientoNotifCovid.as_view(), name='seg_notif_covid_add'),    
    path('sivcovid/seg/upt/<int:pk>', SeguimientoNotifCovidUpdate.as_view(), name='seg_notif_covid_change'),    

    path('con/emp/notifpac/<int:id>', inactivarNotifPaconglemerado, name='paconglomerado_inactivar'),
    path('con/emp/notifpac/list', NotifPaConglomeradoList.as_view(), name='paconglomerado_list'),
    path('con/emp/notifpac/new', NotifPaConglomeradoCreate.as_view(), name='paconglomerado_new'),
    path('con/emp/notifpac/edit/<int:pk>', NotifPaConglomeradoUpdate.as_view(), name='paconglomerado_edit'),
    path('con/emp/conotifpac/new/<int:id>', ContactoAisladoCreate.as_view(), name='contactopacnotif_new'),
    path('con/emp/conotifpac/edit/<int:pk>', ContactoAisladoUpdate.as_view(), name='contactopacnotif_edit'),
    path('con/emp/Segconotifpac/new/<int:id>', SegContactoAisladoCreate.as_view(), name='segcontactopacnotif_new'),
    path('con/emp/segconotifpac/edit/<int:pk>', SegContactoAisladoUpdate.as_view(), name='segcontactopacnotif_edit'),
    path('iec/confconglo/list', ConfigConglomeradoList.as_view(), name='config_conglomerado_list'),
    path('iec/confconglo/new', ConfigConglomeradoCreate.as_view(), name='config_conglomerado_new'),
    path('iec/confconglo/edit/<int:pk>', ConfigConglomeradoUpdate.as_view(), name='config_conglomerado_edit'),
    path('iec/repconglo', ReportConglomerado.as_view(), name='conglomerado_report'),
    path('iec/reponeconglo/<int:pk>', RepConglomerado.as_view(), name='reporte_conglomerado'),
    path('iec/paciente', createNewPac, name='paciente_new'),     
    path('iec/estadsintomacovid', GrafSintomasCovid.as_view(), name='sintomas_covid_est'),
    path('iec/estadcovidbarrio', GrafCovidBarrio.as_view(), name='paccovid_barrio_est'),
    path('iec/estadcovidcoom', GrafCoomorbCovid.as_view(), name='paccovid_coomorbilidad_est'),
    path('iec/geoloc', geolocFichasIEC, name='geoloc_iec'),
    path('pac/busq', busqpaciente, name='busqpac'),

    
] 

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

suisa/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('cnf.urls', namespace='config')),
    path('sint/', include('sint.urls', namespace='sint')),
    path('den/', include('den.urls', namespace='den')),    
    path('cvd/', include('cvd.urls', namespace='cvd')),
    path('bai/', include('bai.urls', namespace='bai')), #Rips
    path('lab/', include('lab.urls', namespace='lab')),
    path('mlr/', include('mlr.urls', namespace='mlr')),
    path('sam/', include('sam.urls', namespace='sam')),    
    path('pai/', include('pai.urls', namespace='pai')),    
    path('aseg/', include('aseg.urls', namespace='aseg')),
    path('pqrs/', include('pqrs.urls', namespace='pqrs')),
    path('ruaf/', include('ruaf.urls', namespace='ruaf')),    
    path('seguridad/', include('seguridad.urls', namespace='seguridad')),    
    path('res4505/', include('res4505.urls', namespace='res4505')), 
    path('admin/', admin.site.urls),

    

] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

cvd/templates/cvd/fichacontactocasosempresa_form.html
{% extends 'base/basecvd.html' %}

{% block page_content %}



    {% if obj %}
    <form  method='POST' role='form' action = "{% url 'cvd:contactopacnotif_edit' obj.pk %}"> 
    {% else %}  
    <form  method='POST' role='form' action = "{% url 'cvd:contactopacnotif_new' idnotifcong %}">
    {% endif %}
        {% csrf_token %}
              <div class="col-xl-12 col-md-12 mb-12">
                {% if obj %}
                  <div class="card border-left-warning shadow h-100 py-2">
                {% else %}    
                  <div class="card border-left-success shadow h-100 py-2">
                 {%  endif %}   
                    <div class="card-body">
                      <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                          <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                              {% if obj %} Editar {% else %} Nuevo {% endif %} Contacto : {{notifcong}}
                           </div>                      
                           <div class="dropdown-divider"></div> 
                            <div class="row">
                              <input type="hidden" name="notifPaConglomerado" value = "{{notifcong.pk}}">
                                  <div class="form-group col-4">
                                        <label for="id_paciente">Contacto</label>
                                        {{form.paciente}}     
                                  </div>
                                  <div class="form-group col-3">
                                        <label for="id_cargo">Cargo</label>
                                        {{form.cargo}}     
                                  </div>
                                  <div class="form-group col-2">
                                        <label for="id_edad">Edad</label>
                                        {{form.edad}}     
                                  </div>
                            </div>
                            <div class="row">
                              <div class="form-group col-3">
                                        <label for="id_municipio">Municipio</label>
                                        {{form.municipio}}                               
                                  </div> 
                                  <div class="form-group col-3">
                                        <label for="id_eps">EPS</label>
                                        {{form.eps}}                               
                                  </div>
                                  <div class="form-group col-2">
                                        <label for="id_feciniaislamiento">F. Aislamiento</label>
                                        {{form.feciniaislamiento}}                               
                                  </div>
                                  
                                  <div class="form-group col-2">
                                        <label for="id_fechafinaislamiento">F. Finaliza Aislamiento</label>
                                        {{form.fechafinaislamiento}}                               
                                  </div>
                                  
                            </div>
                            <div class="row">
                                  <div class="form-group col-3">
                                        <label for="id_diasaislamiento">Cant. Días Aislamiento</label>
                                        {{form.diasaislamiento}}                               
                                  </div>

                                  <div class="form-group col-3">
                                        <label for="id_resultado">Val Medicina general por su EPS </label>
                                        {{form.valmedicagral}}                               
                                  </div>
                                  <div class="form-group col-2">
                                        <label for="id_aislaconincapacidad">Incapacidad?</label>
                                        {{form.aislaconincapacidad}}                               
                                  </div>
                            </div>
                            <div class="row">
                                  <div class="form-group col-2">
                                        <label for="id_requiereprueba">Requiere prueba</label>
                                        {{form.requiereprueba}}                               
                                  </div>
                                  <div class="form-group col-2">
                                        <label for="id_fechatomamuestra">F. Toma Muestra</label>
                                        {{form.fechatomamuestra}}                               
                                  </div>
                                  <div class="form-group col-2">
                                        <label for="id_resultado">Resultado</label>
                                        {{form.resultado}}                               
                                  </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-6">
                                        <label for="id_motivo">Motivo de Aislamiento</label>
                                        {{form.motivo}}                               
                                </div> 
                                <div class="form-group col-6">
                                        <label for="id_descripcion">Descripción</label>
                                        {{form.descripcion}}                               
                                </div>                                   
                            </div>


                              {% if obj %}
                      
                      <div class="col-12" id="prueba"> {# Grilla de Seguimientos #}
                      <div class="row">
                        <h3>Seguimientos</h3>
                      </div>                    

                        <div class="buttons-toolbarcon">
                        <a class="dropdown-item" href="{% url 'cvd:segcontactopacnotif_new' obj.pk %}"> <span class="fa fa-calendar-plus"></span>Nuevo</a>
                       </div>

                        <table data-toggle="table"
                        data-pagination="true"
                        data-search="true"
                        data-show-columns="true"
                        data-toolbar=".buttons-toolbarcon"
                        data-locale="es-MX"
                        data-show-toggle="true"
                        data-show-fullscreen="true">
                        <thead>   
                          <th>Fecha</th>
                          <th>Sintomas</th>
                          <th>Tos</th>                      
                          <th>Fiebre</th>
                          <th>Odinofagia</th>
                          <th>Dif Respirar</th>
                          <th>Fatiga</th>
                          <th>Hospitalizado</th>                                                    
                          <th>Observación</th>                                                    

                          <th class="all">Acciones</th> 
                        </thead>  
                        <tbody>
                          {% for item in seguimiento %}
                            <tr>
                                <td>{{item.fecha|date:"d/m/Y"}}</td>                            
                                <td> {{item.sintomas}}</td>                         
                                <td> {{item.tos}}</td>                     
                                <td> {{item.Fiebre}}</td>
                                <td> {{item.odinofagia}}</td>
                                <td> {{item.dificultadrespirar}}</td>
                                <td> {{item.fatiga}}</td>
                                <td> {{item.hospitalizado}}</td>
                                <td> {{item.observacion}}</td>

                                <td>
                                  <a href="{% url 'cvd:segcontactopacnotif_edit' item.pk %}" class="btn btn-warning btn-circle"><i class="far fa-edit"></i></a>
                                </td>
                              </tr>                   
                          {% endfor %}
                        </tbody>

                      </table>                                     
                    </div> <!--fin contactos--> 
                    {% endif %}

                             {# <!  {{form.as_p}}  -->                #}
                           
                           <div class="dropdown-divider"></div>
                             <div class="row">
                               <div class="col">
                                 <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>
                                <a class="btn btn-success" href="{% url 'cvd:paconglomerado_edit' idnotifcong %}">Cancelar</a>                               
                               </div>
                             </div> 
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
    </form>

	
{% endblock page_content %}

{% block js_page %}

<script>


$(function(){

  $("#id_feciniaislamiento, #id_fechafinaislamiento, #id_fechatomamuestra").datetimepicker({
    format:'d/m/Y',
    timepicker:false
  });
  
    $('#id_paciente').select2({
      placeholder: "Seleccione un Paciente",
      allowClear: true
    });
       
 });

function inactivar(id)
  {
    var data={id:id};
    data= JSON.stringify(data);
    var token = "{{ csrf_token }}";
    //alert("data" + token);
    $.ajax({
      headers : {"X-CSRFToken":token},
      type:"POST",
      url:"con/emp/notifpac/"+id,
      data:data,
      success:function(response){
        if(response === "OK")
        {
          location.reload(true);
        }
        else
        {
          mensaje("Error intentando cambiar el estado del Cliente");
        }
      },
      error: function(jqXHR, textStatus, errorThrow){
        console.log(textStatus, errorThrow);
        mensaje(errorThrow,'red');
        cerrar_modal();
      }
    });
  }


 </script> 
{% endblock js_page %}

cvd/templates/cvd/fichaiec_list.html
{% extends 'base/basecvd.html' %}
{% load static %}
{% block page_content %}
	  <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Listado de Fichas IEC</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">Acciones:</div>
                      <a class="dropdown-item"  href="{% url 'cvd:iec_new' %}"> <span class="fa fa-calendar-plus"></span>Nuevo</a>                      
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                  {% if not obj  %}
                        No hay Pacientes evaluados para Covid
                  {% endif %}
                  <table data-toggle="table"
                    data-pagination="true"
                    data-search="true"
                    data-show-columns="true"
                    data-toolbar=".buttons-toolbar"
                    data-locale="es-MX"
                    data-show-toggle="true"
                    data-show-fullscreen="true">
                    <thead>   
                      <th>Fecha</th>
                      <th>Ident</th>
                      <th>Nombres y Apellidos</th> 
                      <th>Dirección</th> 
                      <th>Teléfono</th>                                            
                      <th>F. Toma Mx</th> 
                      <th>Tipo Mx</th> 
                      <th>Result Mx</th> 
                      <th>Estado</th>
                      <th class="all">Acciones</th> 
                    </thead>  
                    <tbody>
                      {% for item in obj %}
                        <tr>
                            <td>{{item.fecha|date:"d/m/Y"}}</td>                            
                            <td> {{item.paciente.tipodoc.codigo}}:{{item.paciente.identificacion}}</td>
                            <td>{{item.paciente}}</td>
                            <td>{{item.paciente.direccion}}</td>                            
                            <td>{{item.paciente.telefono}}</td>                    
                            <td>{{item.fechaprimuestra|date:"d/m/Y"}}</td>                            
                            <td>{{item.muestra}}</td>
                            <td> P Rápida:{{item.resfilarray}}   PCR:{{item.respcr}}  </td>
                            <td> {{ item.estadoiec }} </td>
                            <td>
                              <a href="{% url 'cvd:iec_edit' item.pk %}" class="btn btn-warning btn-circle"><i class="far fa-edit"></i></a>
                             
                               <a href="{% url 'cvd:ver_fichaiec' item.pk%}"><img class="img-profile rounded-circle" src="{% static 'base/img/desplamientos.png' %}"></a> 
                            </td>
                          </tr>                   
                      {% endfor %}
                    </tbody>

                  </table>
                </div>
            </div>
{% endblock page_content %}

cvd/templates/cvd/segcontactosview_form.html
{% extends 'base/basecvd.html' %}
{% block page_content %}

<div class="col-xl-12 col-md-12 mb-12">                    
    <div class="card border-left-success shadow h-100 py-2">    
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                 <p>Gestión seguimiento a contactos del paciente:  {{obj.fichaiec.paciente}}</p> 
               </div>                      
               <div class="dropdown-divider"></div> 

					       <div class="col-12"> {# Grilla de la movilidad #}
	               		<div class="row"> 
	                       	<div class="form-group col-10">
	                             <h4>Contacto: {{obj.paciente}}</h4>  	                            
	                        </div>                         
	                    </div> 
	               </div>

                  <div class="dropdown-divider"></div> 
                  <div class="col-12">
                  <div class="row"> {# Grilla de la movilidad o desplazamiento #}
                      <div class="col-5" id="prueba">
                          <div class="row">
                            <h3>Desplazamientos</h3>
                          </div>
                         <div class="row">

                         	<div class="buttons-toolbar">
                          <a class="dropdown-item" href="{% url 'cvd:desplacontacto_new' obj.pk %}"> <span class="fa fa-calendar-plus"></span>Nuevo</a>
                       	 </div>

                         	<table data-toggle="table"
                          data-pagination="true"
                          data-search="true"
                          data-show-columns="true"
                          data-toolbar=".buttons-toolbar"
                          data-locale="es-MX"
                          data-show-toggle="true"
                          data-show-fullscreen="true">
                          <thead>   
                            <th>Pais</th>
                            <th>Departamento</th>                           
                            <th>Ciudad</th>                            
                            <th class="all">Acciones</th> 
                          </thead>  
                          <tbody>
                            {% for item in desplaza %}
                              <tr>
                                  <td>{{item.pais}}</td> 
                                  <td>{{item.departamento}}</td>
                                  <td> {{item.ciudad}}</td>
                                  <td>
                                    <a href="{% url 'cvd:desplacontacto_edit' item.pk %}" class="btn btn-warning btn-circle"><i class="far fa-edit"></i></a>
                                  </td>
                                </tr>                   
                            {% endfor %}
                          </tbody>

                        </table>
                       </div>
                    </div>
                   </div> 
    
                  <div class="row"> {# Grilla de los seguimintos #}    

                  <div class="col-9" id="prueba"> {# Grilla de contactos #}
                      <div class="row">
                        <h3>Seguimientos</h3>
                      </div>
                    <div class="row">

                    <div class="buttons-toolbarcon">
                    <a class="dropdown-item" href="{% url 'cvd:seguimientocontacto_new' obj.pk %}"> <span class="fa fa-calendar-plus"></span>Nuevo</a>
                   </div>

                    <table data-toggle="table"
                    data-pagination="true"
                    data-search="true"
                    data-show-columns="true"
                    data-toolbar=".buttons-toolbarcon"
                    data-locale="es-MX"
                    data-show-toggle="true"
                    data-show-fullscreen="true">
                    <thead>   
                      <th>No.</th>                      
                      <th>Fecha</th>
                      <th>sintomatico</th>
                      <th>Tos</th>                      
                      <th>Fiebre</th>   
                      <th>odinofagia</th>   
                      <th>Dif Respi</th>   
                      <th>Adinamia</th>   
                      <th>Hospitalizado</th>                         
                      <th class="all">Acciones</th> 
                    </thead>  
                    <tbody>
                      {% for item in segcon %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{item.fecha|date:"d/m/Y H:m:s"}}</td>                            
                            <td> {{item.sintomatico}}</td>                         
                            <td> {{item.tos}}</td>                     
                            <td> {{item.fiebre}}</td>
                            <td> {{item.odinofagia}}</td>
                            <td> {{item.difrespirar}}</td>                            
                            <td> {{item.adinamia}}</td>
                            <td> {{item.hospitalizado}}</td>
                            <td>
                              <a href="{% url 'cvd:seguimientocontacto_edit' item.pk %}" class="btn btn-warning btn-circle"><i class="far fa-edit"></i></a>
                            </td>
                          </tr>                   
                      {% endfor %}
                    </tbody>
                  </table>
                  </div>
                 </div>
                </div> <!--fin contactos--> 
                </div>
                <div class="row">
                   <a class="btn btn-primary" href="{% url 'cvd:contacto_list' %}">Aceptar</a>
                </div>
            </div>
          </div>
        </div>           
    </div>
</div>

{% endblock page_content %}