bai/urls.py
from django.urls import path
from .views import importCie10, DiagnosticoList, importRips, Grafdiagnosticoscie10, Home, \
DiagnosticoUpdate, DiagnosticoCreate, Archivocontrolist, Archivoconsultalist, ListadoDiagnostico, \
georrefenciarDiagCE, geolocMapaCalorDiagCE, mapaCalarDiagCE, listarRipsCargados

app_name='bai'


urlpatterns = [
	path('', Home.as_view(), name='home'),
	path('importcie10', importCie10, name='Import_cie10'),
	path('rips', importRips, name='importar_rips'),
	path('cie10/estcoom', Grafdiagnosticoscie10.as_view(), name='estadistica_cie10'),
	path('cie10', DiagnosticoList.as_view(), name='cie10list'),
	path('cie10/edit/<int:pk>', DiagnosticoUpdate.as_view(), name='cie10_edit'),
	path('cie10/new', DiagnosticoCreate.as_view(), name='cie10_new'),
	path('rips/ctrl', Archivocontrolist.as_view(), name='rips_control'),
	path('rips/listar/<int:id>', listarRipsCargados, name='rips_listar'),
	path('rips/ce', Archivoconsultalist.as_view(), name='rips_consulta'),
	path('rips/grce', ListadoDiagnostico.as_view(), name='georref_ce'),
	path('rips/grce/<int:iddiag>', georrefenciarDiagCE, name='georref_ce_map'),
	path('rips/grmcce/<int:iddiag>', geolocMapaCalorDiagCE, name='georref_mapcalor_ce'),
	path('rips/mapacalorce/<int:iddiag>', mapaCalarDiagCE, name='mapcalor_ce'),





]

pai/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from cnf.views import Sin_privilegio
from django.views import generic

from .views import importarRediarios, RediarioList, GrafLaborartio, GrafVacunaIps, \
GrafPaiDosisAplicadas, RediarioCreate, RediarioUpdate, RediarioListAjax, RediarioPrint, \
GrafVacunaModalidad, GrafVacunaEtapa, GrafTipoPoblacion, GrafTipoSexo, PrincipalPai, \
importarRediariosPaiRegular, listar_rediario_regular


app_name='pai'

urlpatterns = [
path('', PrincipalPai.as_view(), name='home'),
path('rediario/import', importarRediarios, name='importar_rediarios'),
path('red/import/paireg', importarRediariosPaiRegular, name='import_red_pai_reg'),
path('rediario/reg/list', listar_rediario_regular, name='rediario_reg_list'),

path('rediario/list/', RediarioList.as_view(), name='rediario_list'),
path('rediario/print/<int:id>', RediarioPrint.as_view(), name='Imprimir_datos_vacuna'),
path('rediario/search/<str:dato>', RediarioListAjax.as_view(), name='rediario_search'),
path('rediario/create', RediarioCreate.as_view(), name='rediario_new'),
path('rediario/update/<int:pk>', RediarioUpdate.as_view(), name='rediario_edit'),
path('estadistica/lab', GrafLaborartio.as_view(), name='estlaboratorio'),
path('estadistica/ips', GrafVacunaIps.as_view(), name='estips'),
path('estadistica/modalidad', GrafVacunaModalidad.as_view(), name='estmodalidad'),
path('estadistica/nrodosis', GrafPaiDosisAplicadas.as_view(), name='estnrodosis'),
path('estadistica/etapa', GrafVacunaEtapa.as_view(), name='estapa'),
path('estadistica/tipob', GrafTipoPoblacion.as_view(), name='tipo_poblacion'),
path('estadistica/sexo', GrafTipoSexo.as_view(), name='tipo_sexo'),





#path('propietario', PropietarioList.as_view(), name='propietario_list'),

]

if settings.DEBUG:
	from django.conf.urls.static import static
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

suisa/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('cnf.urls', namespace='config')),
    path('sint/', include('sint.urls', namespace='sint')),
    path('den/', include('den.urls', namespace='den')),    
    path('cvd/', include('cvd.urls', namespace='cvd')),
    path('bai/', include('bai.urls', namespace='bai')), #Rips
    path('lab/', include('lab.urls', namespace='lab')),
    path('mlr/', include('mlr.urls', namespace='mlr')),
    path('sam/', include('sam.urls', namespace='sam')),    
    path('pai/', include('pai.urls', namespace='pai')),    
    path('aseg/', include('aseg.urls', namespace='aseg')),
    path('pqrs/', include('pqrs.urls', namespace='pqrs')),
    path('ruaf/', include('ruaf.urls', namespace='ruaf')),    
    path('seguridad/', include('seguridad.urls', namespace='seguridad')),    
    path('res4505/', include('res4505.urls', namespace='res4505')), 
    path('admin/', admin.site.urls),

    

] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

pai/models.py
from django.db import models
from django.forms import model_to_dict

# Create your models here.
from cnf.models import Ips, ClaseModelo2, Paciente, Periodo

class VacunaCovid(ClaseModelo2):
	fecha = models.DateField() 
	ips = models.ForeignKey(Ips, on_delete=models.CASCADE)
	saldovacuna = models.IntegerField()
	ingreso = models.IntegerField()
	devolucion = models.IntegerField()
	vacunadisponible = models.IntegerField()
	prograintramural = models.IntegerField()
	prograextramural = models.IntegerField()	
	dosisaplimay80intramural = models.IntegerField()
	dosisaplitrasalintramural = models.IntegerField()
	dosisaplimay80extramural = models.IntegerField()
	dosisaplitrasalextramural = models.IntegerField()
	totalintramural = models.IntegerField()
	totalextramural = models.IntegerField()
	nroequivacintramural = models.IntegerField()
	nroequivacextramural = models.IntegerField()
	nrohorahabpuntovacextra = models.FloatField()
	nrohorahabpuntovacintra = models.FloatField()
	rendihoraintramural = models.FloatField()
	rendihoraextramural = models.FloatField()
	producequipoextramural = models.FloatField()
	producequipointramural = models.FloatField()
	porcumplmetaprogintra = models.FloatField()
	porcumplmetaprogextra = models.FloatField()
	porcumpldiariointra = models.FloatField()
	porcumpldiarioextra = models.FloatField()
	nrodesespersalud = models.IntegerField()
	nrodesesmay80 = models.IntegerField()
	nroprobeventoadverso = models.IntegerField()
	nrobiolperdido = models.IntegerField()
	nrobiolperdido = models.IntegerField()
	nroesavisnotificados = models.IntegerField()
	nrodosispaiweb = models.IntegerField()


	class Meta:
		verbose_name_plural="Vacunación Covid19"

	def save(self):
		self.vacunadisponible = (self.saldovacuna + self.ingreso) - self.devolucion
		self.totalintramural = self.dosisaplimay80intramural + self.dosisaplitrasalintramural
		self.totalextramural = self.dosisaplimay80extramural + self.dosisaplitrasalextramural
		if (self.nroequivacextramural * self.nrohorahabpuntovacextra) != 0:
			self.producequipoextramural = self.totalextramural / (self.nroequivacextramural * self.nrohorahabpuntovacextra)
			self.porcumpldiarioextra = (self.totalextramural / (self.nroequivacextramural * self.nrohorahabpuntovacextra * 8))*100

		if (self.nroequivacintramural * self.nrohorahabpuntovacintra) != 0:
			self.producequipointramural = self.totalintramural / (self.nroequivacintramural * self.nrohorahabpuntovacintra)
			self.porcumpldiariointra = (self.totalintramural / (self.nroequivacintramural * self.nrohorahabpuntovacintra * 8))*100

		if self.prograextramural != 0:
			self.porcumplmetaprogextra = (self.totalextramural / self.prograextramural) * 100
		if self.prograintramural != 0:
			self.porcumplmetaprogintra = (self.totalintramural / self.prograintramural) * 100		

		super(VacunaCovid, self).save() #llamar al metodo guardar del padre

	def __str__(self):
		return "{}-{}".format(self.fecha,self.ips)

class RediarioCargado(ClaseModelo2):
	fecha = models.DateField()
	file_name = models.FileField(upload_to='rediario')
	uploaded =models.DateField(auto_now_add=True)
	activated= models.BooleanField(default=False)

	def save(self):
		#self.uc = instance.request.user
		super(RediarioCargado, self).save()

	def __str__(self):
		return f"Id del Archivo {self.id}"


class RediarioPaiRegCargado(ClaseModelo2):
	fecha = models.DateField()
	periodo = models.ForeignKey(Periodo, on_delete=models.CASCADE)
	file_name = models.FileField(upload_to='rediario')
	uploaded =models.DateField(auto_now_add=True)
	activated= models.BooleanField(default=False)
	ips = models.ForeignKey(Ips, on_delete=models.CASCADE)

	class Meta:
		verbose_name='Import rediario PAI Regular'
	

	def save(self):
		#self.um = self.request.user
		super(RediarioPaiRegCargado, self).save()

	def __str__(self):
		return f"Id del Archivo {self.id}"


class Rediario(ClaseModelo2):
	fecha = models.DateField()
	tipodoc = models.CharField(max_length=2)
	identificacion = models.CharField(max_length=20)
	fechanac = models.DateField()
	tipoedad = models.CharField(max_length=20)
	edad = models.FloatField()
	sexo = models.CharField(max_length=10)
	apellido1 = models.CharField(max_length=50)
	apellido2 = models.CharField(max_length=50, null=True, blank=True)
	nombres = models.CharField(max_length=100)
	razonsocial = models.CharField(max_length=210)
	regimen = models.CharField(max_length=50, null=True, blank=True)
	eapb = models.CharField(max_length=50, null=True, blank=True)
	departamentores = models.CharField(max_length=50, null=True, blank=True)
	municipiores = models.CharField(max_length=50, null=True, blank=True)
	area = models.CharField(max_length=30, null=True, blank=True)
	barrio = models.CharField(max_length=80, null=True, blank=True)
	direccion = models.CharField(max_length=100, null=True, blank=True)
	telefono = models.CharField(max_length=80, null=True, blank=True)
	grupoetnico = models.CharField(max_length=80, null=True, blank=True)
	desplazado = models.CharField(max_length=10, null=True, blank=True)
	discapacitado = models.CharField(max_length=20, null=True, blank=True)
	correoelectronico = models.CharField(max_length=100, null=True, blank=True)
	condiccusuaria = models.CharField(max_length=200, null=True, blank=True)
	fechaprobparto = models.DateField(null=True, blank=True)
	etapa = models.CharField(max_length=80)
	tipopoblacion = models.CharField(max_length=300)
	dosisaplicada = models.CharField(max_length=80)
	laboratorio = models.CharField(max_length=50)
	lotebiologico = models.CharField(max_length=50, null=True, blank=True)
	jeringa = models.CharField(max_length=80, null = True, blank = True)
	lotejeringa = models.CharField(max_length=50, null=True, blank=True)
	eventoadverso = models.CharField(max_length=2, default='NO', null=True, blank=True)
	vacunador = models.CharField(max_length=100, null=True, blank = True)
	municipio = models.CharField(max_length=50, null=True, blank=True)
	nombreIps = models.CharField(max_length=250)
	novedad = models.CharField(max_length=80, null=True, blank=True)
	descNovedad = models.CharField(max_length=250, null=True, blank=True)
	modalidad = models.CharField(max_length=30, null=True, blank=True)
	observacion = models.TextField(null=True, blank=True)
	reportado = models.CharField(max_length=2, null=True, blank=True)

	class Meta:
		verbose_name = 'Rediario'
		verbose_name_plural = 'Rediarios'
		ordering=['fecha']

	def save(self):
		razsoc = self.nombres
		razsoc = razsoc + " " + self.apellido1
		if self.apellido2 != "" or self.apellido2 != "0" or self.apellido2 != 0:
			pass
		else: 
			razsoc = razsoc + " " + self.apellido2

		self.razonsocial = razsoc.upper()
	
		super(Rediario, self).save()


	def __str__(self):
		return "{} - {} {} {}".format(self.fecha, self.apellido1, self.apellido2, self.nombres)

	def toJSON(self):
		item = model_to_dict(self)
		return item
		

class Biologico(ClaseModelo2):
	codigo = models.CharField(max_length=10)
	descripcion = models.CharField(max_length=80)
	usadiluyente = models.BooleanField(default=False)
	usajeringa = models.BooleanField(default=True)

	def __str__(self):
		return "{}".format(self.descripcion)

class Dosisbiologico(ClaseModelo2):
	codigo=models.CharField(max_length=3)
	descripcion=models.CharField(max_length=80)
	biologico = models.ForeignKey(Biologico, on_delete=models.CASCADE)

	def __str__(self):
		return "{}".format(self.descripcion)

class Jeringas(ClaseModelo2):
	codigo=models.CharField(max_length=20)
	descripcion = models.CharField(max_length=80)

	def __str__(self):
		return "{}".format(self.descripcion)

class Rediarioregular(ClaseModelo2):
	SINO = (
        ('SI', 'Si'),
        ('NO', 'No'),        
    )
	ips = models.ForeignKey(Ips, on_delete=models.CASCADE)
	fecha = models.DateField()
	paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, related_name='dato_paciente')
	edadanios=models.IntegerField(default=0)
	edadmes=models.IntegerField(default=0)
	edaddias=models.IntegerField(default=0)
	edadtotalmeses=models.IntegerField(default=0)
	desplazado = models.CharField(max_length=2, choices=SINO, null=True, blank=True)
	discapacitado = models.CharField(max_length=2, choices=SINO, null=True, blank=True)
	fallecido = models.CharField(max_length=2, choices=SINO, null=True, blank=True)
	victima = models.CharField(max_length=2, choices=SINO, null=True, blank=True)
	estudiante = models.CharField(max_length=2, choices=SINO, null=True, blank=True)
	autorizallamada = models.CharField(max_length=2, choices=SINO, null=True, blank=True)
	autorizaenvemail = models.CharField(max_length=2, choices=SINO, null=True, blank=True)
	madre = models.ForeignKey(Paciente, on_delete=models.CASCADE, null=True, blank=True, related_name='dato_madre')
	cuidador = models.ForeignKey(Paciente, on_delete=models.CASCADE, null=True, blank=True, related_name='dato_cuidador')
	namevacunador = models.CharField(max_length=80, null = True, blank=True)
	registroenpaiweb = models.CharField(max_length=2, choices=SINO, null=True, blank=True)
	observacion = models.TextField(null=True, blank=True)

	#def get_absolute_url(self):
	#	return reverse('library:book', kwargs={'pk':self.pk})

class RediarioRegBiologico(ClaseModelo2):
	rediarioregular = models.ForeignKey(Rediarioregular, on_delete=models.CASCADE)
	biologico = models.ForeignKey(Biologico, on_delete=models.CASCADE)
	nrofrascos = models.IntegerField(default=0, null=True, blank=True)
	dosisbiologico = models.ForeignKey(Dosisbiologico, on_delete=models.CASCADE, null=True, blank=True)
	loteBiologico = models.CharField(max_length=20, null=True, blank=True)
	jeringa = models.ForeignKey(Jeringas, on_delete=models.CASCADE, null=True, blank=True)
	lotejeringa = models.CharField(max_length=20, null=True, blank=True)
	lotediluyente = models.CharField(max_length=20, null=True, blank=True)











	







	

pai/forms.py
from django import forms

from .models import RediarioCargado, Rediario, RediarioPaiRegCargado

class ImportFileForm(forms.ModelForm):	
	class Meta:
		model=RediarioCargado		
		fields=['fecha','file_name']
		exclude=['uploaded','activated','um','uc','fm','fc']

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs) #para que se inicialice
		for field in iter(self.fields):
			self.fields[field].widget.attrs.update({				
				'class':"form-control" #colocar la clase de bootsTrap a todos los controles o campos
				
			})

class ImportFilePaiRegForm(forms.ModelForm):	
	class Meta:
		model=RediarioPaiRegCargado		
		fields=['fecha','periodo','file_name', 'ips']
		exclude=['uploaded','activated','um','uc','fm','fc']

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs) #para que se inicialice
		for field in iter(self.fields):
			self.fields[field].widget.attrs.update({				
				'class':"form-control" #colocar la clase de bootsTrap a todos los controles o campos
				
			})

class RediarioCreateForm(forms.ModelForm):	
	class Meta:
		model=Rediario			
		exclude=['um','uc','fm','fc','razonsocial', 'reportado', 'estado']

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs) #para que se inicialice
		for field in iter(self.fields):
			if field.lower() == 'observacion'.lower():
				self.fields[field].widget.attrs.update({				
				'class':"form-control", #colocar la clase de bootsTrap a todos los controles o campos
				'rows':"2"
				})
			else:
				self.fields[field].widget.attrs.update({				
				'class':"form-control" #colocar la clase de bootsTrap a todos los controles o campos
				
				})

pai/templates/pai/estPaivacunasform.html
{% extends 'base/basepai.html' %}

{% block page_content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div id="container">
                
            </div>
        </div>
    </div>

   
</div>
    
{% endblock page_content %}

{% block js_page %}
<script>

//datos=[{'name': 'OBRERO', 'y': 1},{'name': 'ZAMANES', 'y': 2}] 

Highcharts.chart('container', {
    chart: {
        plotBackgroundColor: null,
        plotBorderWidth: null,
        plotShadow: false,
        type: 'pie'
    },
    title: {
        text: 'ESTADISTICA DE PACIENTES COVID POR BARRIO'
    },
    tooltip: {
        pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
    },
    accessibility: {
        point: {
            valueSuffix: '%'
        }
    },
    plotOptions: {
        pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            dataLabels: {
                enabled: true,
                format: '<b>{point.name}</b>: {point.percentage:.1f} %'
            }
        }
    },
    series: [{
        name: 'Brands',
        colorByPoint: true,
        data: {{ barrio|safe }} 

    }]
});
    
</script>



    
{% endblock js_page %}

pai/templates/pai/importrediariospaireg.html
{% extends 'base/basepai.html' %}
{% block page_content %}
<div class="card-body">
<h1> Importar Rediarios </h1>
<form action="" method="POST" role='form' enctype="multipart/form-data">
    {% csrf_token %} 
		<div class="dropdown-divider"></div> 
        <div class="col-xl-6 col-md-12 mb-6">
           	<div class="dropdown-divider"></div> 
                <div class="row">
                     <div class="form-group col-4">
                         <label for="id_fecha">Fecha</label>
                           <br>
                              {{form.fecha}}                               
                          </div> 

                          <div class="form-group col-8">
                             <label for="id_periodo">Periodo</label>
                             <br>
                              {{ form.periodo }}                                    
                          </div>
                </div>
                <div class="row">
                	<div class="form-group col-12">
                      <label for="id_ips">Ips</label>
                        <br>
                         {{ form.ips }}                                    
                  </div>
                </div>
                <div class="row">
                	<div class="form-group col-12">
                    <label for="id_file_name">Archivo</label>
                     <br>
                      {{ form.file_name }}                                    
                  </div>
                </div>
                                  
                                  
                
     
        </div>
        
           <div class="barra">
       	  <div class="barra_azul" id="barra_estado"></div>
       	  <span></span>
       </div>
              
    <button type="submit" class="btn btn-primary">Importar</button>
</form>
</div>
	
{% endblock page_content %}

{% block js_page %}
<script>
	$('.custom-file-input').on('change', function(event) {
	    var inputFile = event.currentTarget;
	    $(inputFile).parent()
	        .find('.custom-file-label')
	        .html(inputFile.files[0].name);
	}); 

 $("#id_fecha").datetimepicker({
    format:'d/m/Y',
    timepicker:false
  });

	
</script>
{% endblock %}

pai/templates/pai/rediariocreateform.html
{% extends 'base/basepai.html' %}
{% block page_content %}

 {% if obj %}
  <form  method='POST' role='form' action = "{% url 'pai:rediario_edit' obj.pk %}"> 
    {% else %}  
    <form  method='POST' role='form' action = "{% url 'pai:rediario_new'  %}">
    {% endif %}
    {% csrf_token %}

	<div class="col-xl-12 col-md-12 mb-12">
        <div class="card border-left-warning shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                              {% if obj %} Seguimiento {% else %} Nuevo {% endif %} Registro diario
                        </div>   

                       <!-- {{ form.as_p }} -->
                        <div class="row">
                            <div class="form-group col-2">
                               <label for="id_fecha">Fecha de Vacunación</label>
                              {{form.fecha}}                               
                            </div>  
                            <div class="form-group col-2">
                               <label for="id_tipodoc">Documento</label>
                              {{form.tipodoc}}                               
                            </div>
                            <div class="form-group col-2">
                               <label for="id_identificacion">Identificación</label>
                              {{form.identificacion}}                               
                            </div>
                            <div class="form-group col-2">
                               <label for="id_pais">Fecha Nac</label>
                              {{form.fechanac}}                               
                            </div>
                            <div class="form-group col-1">
                               <label for="id_tipoedad">Tipo Edad</label>
                              {{form.tipoedad}}                               
                            </div>
                            <div class="form-group col-1">
                               <label for="id_pais">Edad</label>
                              {{form.edad}}                               
                            </div>
                            <div class="form-group col-2">
                               <label for="id_pais">Sexo</label>
                              {{form.sexo}}                               
                            </div>                            
                        </div>  
                         <div class="row">                            
                            <div class="form-group col-3">
                               <label for="id_nombres">Nombres</label>
                              {{form.nombres}}                               
                            </div>
                            <div class="form-group col-2">
                               <label for="id_apellido1">Primer Apellido</label>
                              {{form.apellido1}}                               
                            </div>
                            <div class="form-group col-2">
                               <label for="id_apellido2">Segundo Apellido</label>
                              {{form.apellido2}}                               
                            </div>
                            <div class="form-group col-2">
                               <label for="id_regimen">Régimen</label>
                              {{form.regimen}}                               
                            </div>
                            <div class="form-group col-3">
                               <label for="id_eapb">Aseguramiento</label>
                              {{form.eapb}}                               
                            </div>                            
                        </div>  
                        <div class="row">                            
                            <div class="form-group col-2">
                               <label for="id_departamentores">Dpto de residencia</label>
                              {{form.departamentores}}                               
                            </div>
                            <div class="form-group col-2">
                               <label for="id_municipiores">Municipio de residencia</label>
                              {{form.municipiores}}                               
                            </div>
                            <div class="form-group col-2">
                               <label for="id_area">Área</label>
                              {{form.area}}                               
                            </div>
                            <div class="form-group col-2">
                               <label for="id_barrio">Barrio</label>
                              {{form.barrio}}                               
                            </div>
                            <div class="form-group col-2">
                               <label for="id_direccion">Dirección</label>
                              {{form.direccion}}                               
                            </div>  
                            <div class="form-group col-2">
                               <label for="id_telefono">Teléfono</label>
                              {{form.telefono}}                               
                            </div>                          
                        </div> 
                        <div class="row">                            
                            <div class="form-group col-2">
                               <label for="id_grupoetnico">Grupo Étnico</label>
                              {{form.grupoetnico}}                               
                            </div>
                            <div class="form-group col-2">
                               <label for="id_desplazado">Desplazado</label>
                              {{form.desplazado}}                               
                            </div>
                            <div class="form-group col-2">
                               <label for="id_discapacitado">Discapacitado</label>
                              {{form.discapacitado}}                               
                            </div>
                            <div class="form-group col-2">
                               <label for="id_correoelectronico">Correo Electrónico</label>
                              {{form.correoelectronico}}                               
                            </div>
                            <div class="form-group col-2">
                               <label for="id_condiccusuaria">Cond. Usuaria</label>
                              {{form.condiccusuaria}}                               
                            </div>  
                            <div class="form-group col-2">
                               <label for="id_fechaprobparto">Fec. Prob Parto</label>
                              {{form.fechaprobparto}}                               
                            </div>                          
                        </div>  
                        <div class="row">                            
                            <div class="form-group col-1">
                               <label for="id_etapa">Etapa</label>
                              {{form.etapa}}                               
                            </div>
                            <div class="form-group col-2">
                               <label for="id_tipopoblacion">Tipo población</label>
                              {{form.tipopoblacion}}                               
                            </div>
                            <div class="form-group col-2">
                               <label for="id_dosisaplicada">Dosis aplicada</label>
                              {{form.dosisaplicada}}                               
                            </div>
                            <div class="form-group col-2">
                               <label for="id_laboratorio">Laboratorio</label>
                              {{form.laboratorio}}                               
                            </div>
                            <div class="form-group col-2">
                               <label for="id_condiccusuaria">Lote biol</label>
                              {{form.lotebiologico}}                               
                            </div>  
                            <div class="form-group col-2">
                               <label for="id_jeringa">Jeringa</label>
                              {{form.jeringa}}                               
                            </div> 
                            <div class="form-group col-1">
                               <label for="id_lotejeringa">Lote Jer</label>
                              {{form.lotejeringa}}                               
                            </div>                         
                        </div>    
                        <div class="row">                            
                            <div class="form-group col-2">
                               <label for="id_eventoadverso">Evento adverso</label>
                              {{form.eventoadverso}}                               
                            </div>
                            <div class="form-group col-3">
                               <label for="id_vacunador">Vacunador</label>
                              {{form.vacunador}}                               
                            </div>
                            <div class="form-group col-3">
                               <label for="id_municipio">Municipio que reporta</label>
                              {{form.municipio}}                               
                            </div>
                            <div class="form-group col-4">
                               <label for="id_nombreIps">IPS</label>
                              {{form.nombreIps}}                               
                            </div>
                                                
                        </div>      
                        <div class="row">                            
                            <div class="form-group col-2">
                               <label for="id_novedad">Novedad</label>
                              {{form.novedad}}                               
                            </div>
                            <div class="form-group col-3">
                               <label for="id_descNovedad">Desc. Novedad</label>
                              {{form.descNovedad}}                               
                            </div>
                            <div class="form-group col-3">
                               <label for="id_modalidad">Modalidad</label>
                              {{form.modalidad}}                               
                            </div>
                            <div class="form-group col-4">
                               <label for="id_observacion">Observación</label>
                              {{form.observacion}}                               
                            </div>                                                
                        </div>   

                </div> 
             </div>  <!-- Cardbody -->
        </div> 
        <div class="dropdown-divider"></div>
         <div class="row">
           <div class="col">
             <button type="submit" class="btn btn-danger">
                <span class="fa fa-save"></span>Guardar
            </button>
              <a href="{% url 'pai:rediario_list' %}" class="btn btn-success">Cancelar</a>
          
           </div>
         </div> 


        
    </div>
</div>
</form>

{% endblock page_content %}