bai/urls.py
from django.urls import path
from .views import importCie10, DiagnosticoList, importRips, Grafdiagnosticoscie10, Home, \
DiagnosticoUpdate, DiagnosticoCreate, Archivocontrolist, Archivoconsultalist, ListadoDiagnostico, \
georrefenciarDiagCE, geolocMapaCalorDiagCE, mapaCalarDiagCE, listarRipsCargados

app_name='bai'


urlpatterns = [
	path('', Home.as_view(), name='home'),
	path('importcie10', importCie10, name='Import_cie10'),
	path('rips', importRips, name='importar_rips'),
	path('cie10/estcoom', Grafdiagnosticoscie10.as_view(), name='estadistica_cie10'),
	path('cie10', DiagnosticoList.as_view(), name='cie10list'),
	path('cie10/edit/<int:pk>', DiagnosticoUpdate.as_view(), name='cie10_edit'),
	path('cie10/new', DiagnosticoCreate.as_view(), name='cie10_new'),
	path('rips/ctrl', Archivocontrolist.as_view(), name='rips_control'),
	path('rips/listar/<int:id>', listarRipsCargados, name='rips_listar'),
	path('rips/ce', Archivoconsultalist.as_view(), name='rips_consulta'),
	path('rips/grce', ListadoDiagnostico.as_view(), name='georref_ce'),
	path('rips/grce/<int:iddiag>', georrefenciarDiagCE, name='georref_ce_map'),
	path('rips/grmcce/<int:iddiag>', geolocMapaCalorDiagCE, name='georref_mapcalor_ce'),
	path('rips/mapacalorce/<int:iddiag>', mapaCalarDiagCE, name='mapcalor_ce'),





]

mlr/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from cnf.views import Sin_privilegio
from django.views import generic

from .views import importarMalaria, MalariaList, malariaEdit, SegPacMalariaEdit, SegPacMalariaCreate, \
geolocMalaria, geolocMapaCalorMalaria, ConglomeradoMalariaList, ConglomeradoMalariaCreate,\
ConglomeradoMalariaEdit, ConglomeradoPacMalariaCreate, ConglomeradoPacMalariaUpdate, \
SegConglomeradoMalariaUpdate, SegConglomeradoMalariaCreate, FileConglomeradoUpdate, \
FileConglomeradoCreate, GrafComplicacionMlr, GrafMalariaSemEpi, GrafMalariaBarrio, GrafMalariaEPS, \
Home


app_name='mlr'

urlpatterns = [
path('home', Home.as_view(), name='home'),
path('importar', importarMalaria, name='importar_malaria'),
path('malaria', MalariaList.as_view(), name='malaria_list'),
path('malaria/edit/<int:idmalaria>', malariaEdit, name='malaria_edit'),
path('malaria/seg/edit/<int:pk>', SegPacMalariaEdit.as_view(), name='segmalaria_edit'),
path('malaria/seg/new/<int:idmalaria>', SegPacMalariaCreate.as_view(), name='segmalaria_new'),
path('malaria/geoloc', geolocMalaria, name='geoloc_malaria'),
path('malaria/geomapcalor', geolocMapaCalorMalaria, name='geomapcalor_malaria'),
path('conglomerado', ConglomeradoMalariaList.as_view(), name='conglomeradomlr_list'),
path('conglomerado/edit/<int:pk>', ConglomeradoMalariaEdit.as_view(), name='conglomeradomlr_edit'),
path('conglomerado/new', ConglomeradoMalariaCreate.as_view(), name='conglomeradomlr_new'),
path('conglo/pac/new/<int:idconglomerado>', ConglomeradoPacMalariaCreate.as_view(), name='pacconglomlr_new'),
path('conglo/pac/edit/<int:pk>', ConglomeradoPacMalariaUpdate.as_view(), name='pacconglomlr_edit'),
path('mlr/seg/conglo/edit/<int:pk>', SegConglomeradoMalariaUpdate.as_view(), name='segconglomalaria_edit'),
path('mlr/seg/conglo/new/<int:idconglomerado>',SegConglomeradoMalariaCreate.as_view(), name='segconglomalaria_new'),
path('mlr/arch/conglo/edit/<int:pk>', FileConglomeradoUpdate.as_view(), name='fileconglomalaria_edit'),
path('mlr/arch/conglo/new/<int:idconglomerado>',FileConglomeradoCreate.as_view(), name='fileconglomalaria_new'),
path('Graf/complicaciones',GrafComplicacionMlr.as_view(), name='est_complicacion_malaria'),
path('Graf/mlr/semepi',GrafMalariaSemEpi.as_view(), name='est_malaria_semepi'),
path('Graf/mlr/barrio',GrafMalariaBarrio.as_view(), name='est_malaria_barrio'),
path('Graf/mlr/eps',GrafMalariaEPS.as_view(), name='est_malaria_eps'),






]

if settings.DEBUG:
	from django.conf.urls.static import static
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

suisa/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('cnf.urls', namespace='config')),
    path('sint/', include('sint.urls', namespace='sint')),
    path('den/', include('den.urls', namespace='den')),    
    path('cvd/', include('cvd.urls', namespace='cvd')),
    path('bai/', include('bai.urls', namespace='bai')), #Rips
    path('lab/', include('lab.urls', namespace='lab')),
    path('mlr/', include('mlr.urls', namespace='mlr')),
    path('sam/', include('sam.urls', namespace='sam')),    
    path('pai/', include('pai.urls', namespace='pai')),    
    path('aseg/', include('aseg.urls', namespace='aseg')),
    path('pqrs/', include('pqrs.urls', namespace='pqrs')),
    path('ruaf/', include('ruaf.urls', namespace='ruaf')),    
    path('seguridad/', include('seguridad.urls', namespace='seguridad')),    
    path('res4505/', include('res4505.urls', namespace='res4505')), 
    path('admin/', admin.site.urls),

    

] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

mlr/models.py
from django.db import models

# Create your models here.

from cnf.models import ClaseModelo2, Paciente,Evento, UmEdad, Ocupacion, Regimen, Eps, Departamento,\
Municipio, ClasiFinicial, Upgd, CondiccionFinal, SemEpidemiologica, Fuente, Pais, Barrio

from bai.models import Diagnosticos

from lab.models import TipoExamen

class EspecieInf(ClaseModelo2):
	codigo = models.IntegerField()
	descripcion = models.CharField(max_length=50)

	class Meta:
		verbose_name='Especie Infectante'

	def __str__(self):
		return "{}".format(self.descripcion)

class Tratamiento(ClaseModelo2):
	codigo = models.IntegerField()
	descripcion = models.CharField(max_length=100)

	class Meta:
		verbose_name='Tratamientos de Malaria'
		ordering = ['descripcion']

	def __str__(self):
		return "{}".format(self.descripcion)


class Malaria(ClaseModelo2):
	TRIMESTREGES=(
    	('1','Primer trimestre'),
    	('2','Segundo trimestre'),
    	('3','Tercer trimestre'),
    )
	SINO = (
        ('1', 'Si'),
        ('2', 'No'),
    )
	paciente=models.ForeignKey(Paciente, on_delete=models.CASCADE)
	evento=models.ForeignKey(Evento, on_delete=models.CASCADE)
	fec_not = models.DateField()
	semana = models.IntegerField()
	anio = models.IntegerField()
	cod_pre = models.CharField(max_length=20)
	cod_sub = models.CharField(max_length=2)
	edad = models.IntegerField()
	umedad = models.ForeignKey(UmEdad, on_delete=models.CASCADE, null=True, blank=True)
	ocupacion = models.ForeignKey(Ocupacion, on_delete=models.CASCADE, null=True, blank=True)
	regimen = models.ForeignKey(Regimen, on_delete=models.CASCADE)
	eps = models.ForeignKey(Eps, on_delete=models.CASCADE, null=True, blank=True)
	estrato = models.IntegerField(null=True, blank=True)
	gp_discapa = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 
	gp_desplaz = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 
	gp_migrant = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 
	gp_carcela = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 
	gp_gestan = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 
	sem_ges = models.IntegerField(null=True, blank=True) 
	gp_indigen = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 
	gp_pobicbf = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 
	gp_mad_com = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 
	gp_desmovi = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 
	gp_psiquia = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 
	gp_vic_vio = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 
	gp_otros = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 
	fuente = models.ForeignKey(Fuente, on_delete=models.CASCADE, null=True, blank=True)
	paisr = models.ForeignKey(Pais, on_delete=models.CASCADE, null=True, blank=True)
	departamentor = models.ForeignKey(Departamento, on_delete=models.CASCADE, null=True, blank=True)
	municipior = models.ForeignKey(Municipio, on_delete=models.CASCADE, null=True, blank=True)
	fec_con = models.DateField(null=True, blank=True)
	ini_sin = models.DateField(null=True, blank=True)
	clasifinicial = models.ForeignKey(ClasiFinicial, on_delete=models.CASCADE, null=True, blank=True)
	pac_hos = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 
	fec_hos = models.DateField(null=True, blank=True)		
	condiccionfinal = models.ForeignKey(CondiccionFinal, on_delete=models.CASCADE, null=True, blank=True)
	fec_def = models.DateField(null=True, blank=True)
	ajuste = models.CharField(max_length=10, null=True, blank=True)
	fec_ajuste = models.DateField(null=True, blank=True)
	cer_def = models.CharField(max_length=50, null=True, blank=True)
	cbmte = models.ForeignKey(Diagnosticos, on_delete=models.CASCADE, null=True, blank=True)
	telefono = models.CharField(max_length=30, null=True, blank=True)
	nit_upgd = models.CharField(max_length=30, null=True, blank=True)
	upgd = models.ForeignKey(Upgd, on_delete=models.CASCADE, null=True, blank=True)
	vig_activa = models.CharField(max_length=1, choices=SINO, null=True, blank=True)
	sintomatic = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 
	clas_caso = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 
	recrudece = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 	
	trimestre = models.CharField(max_length=1, choices=TRIMESTREGES, null=True, blank=True) 
	tipoexamen = models.ForeignKey(TipoExamen, on_delete=models.CASCADE, null=True, blank=True) 	
	recuento = models.FloatField(null=True, blank=True, default=0)
	gametocito = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 	
	desplazami = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 	
	despla_codpais = models.IntegerField(null=True, blank=True)
	despla_coddep = models.IntegerField(null=True, blank=True)
	despla_codmun = models.IntegerField(null=True, blank=True)
	complicaci = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 
	com_cerebr = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 
	com_renal = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 
	com_hepati = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 
	com_pulmon = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 
	com_hemato = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 
	com_otras = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 
	tratamiento = models.ForeignKey(Tratamiento, on_delete=models.CASCADE, null=True, blank=True)
	f_ini_trat = models.DateField(null=True, blank=True)
	especieinf =  models.ForeignKey(EspecieInf, on_delete=models.CASCADE, null=True, blank=True) 
	resp_diag = models.CharField(max_length=150, null=True, blank=True)
	fec_result = models.DateField(null=True, blank=True)
	result_exa = models.CharField(max_length=100, null=True, blank=True)
	nuevo = models.CharField(max_length=1, choices=SINO, null=True, blank=True) 
	nom_upgd = models.CharField(max_length=150, null=True, blank=True) 
	npais_proce = models.IntegerField(null=True, blank=True)
	ndep_proce = models.IntegerField(null=True, blank=True)
	nmun_proce = models.IntegerField(null=True, blank=True)
	

	class Meta:
		verbose_name_plural="Notificación Casos de Malaria - 465"
		ordering = ['fec_not']

	def __str__(self):
		return "{} - Notificado el: {} Sem: {} Evento: {}".format( self.paciente, self.fec_not, self.semana ,self.evento.descripcion,)


class ImportarMalaria(ClaseModelo2):
	semepidemiologica = models.ForeignKey(SemEpidemiologica, on_delete=models.CASCADE)
	evento = models.ForeignKey(Evento, on_delete=models.CASCADE)
	file_name = models.FileField(upload_to='mlr')
	uploaded =models.DateField(auto_now_add=True)
	activated= models.BooleanField(default=False)

	def save(self):
		#self.uc = instance.request.user
		super(ImportarMalaria, self).save()

	def __str__(self):
		return f"Id del Archivo {self.id}"

class SegPacMalaria(ClaseModelo2):
	SINO = (
        ('1', 'Si'),
        ('2', 'No'),
    )
	malaria = models.ForeignKey(Malaria, on_delete=models.CASCADE)
	fecha= models.DateField()
	hallazgos = models.TextField()
	ctrllarvario = models.CharField(max_length=1, choices=SINO, null=True, blank=True)
	fumigacion = models.CharField(max_length=1, choices=SINO, null=True, blank=True)
	educacion = models.CharField(max_length=1, choices=SINO, null=True, blank=True)
	entregatoldillos = models.CharField(max_length=1, choices=SINO, null=True, blank=True)
	cantolperiesgo = models.IntegerField(default=0)
	cantolcoomorb = models.IntegerField(default=0)
	cantoladulmay = models.IntegerField(default=0)
	cantolmencinco = models.IntegerField(default=0)
	cantolembarazadas = models.IntegerField(default=0)

	class Meta:
		verbose_name_plural="Seguimientos Malaria"

	def __str__(self):
		return "{} - {}".format(self.malaria - self.hallazgos)

class Conglomerado(ClaseModelo2):		
	fechainibrote = models.DateField()
	descripcion = models.TextField()
	barrio = models.ForeignKey(Barrio, on_delete=models.CASCADE, null=True, blank=True)		
	visitado=models.BooleanField(default=False)
	fechavisita = models.DateField(null=True, blank=True)
	nrodecasos=models.IntegerField(null=True, blank=True)

	class Meta:
		verbose_name='Conglomerado de Casos de Malaria'
		ordering=['fechainibrote']

	def __str__(self):
		return "Fecha Brote:{}, Lugar: {}. Nro de casos: {} ".format(self.fechainibrote, self.barrio, self.nrodecasos)


class ConglomeradoMalaria(ClaseModelo2):
	conglomerado = models.ForeignKey(Conglomerado, on_delete=models.CASCADE)
	malaria = models.ForeignKey(Malaria, on_delete=models.CASCADE)

	class Meta:
		verbose_name='Casos de Malaria en Conglomerado'

	def __str__(self):
		return "Conglomerado: {} - Paciente: {}".format(self.conglomerado, self.malaria)


class SegCongloMalaria(ClaseModelo2):
	SINO = (
        ('1', 'Si'),
        ('2', 'No'),
    )
	conglomerado = models.ForeignKey(Conglomerado, on_delete=models.CASCADE)
	fecha= models.DateField()
	hallazgos = models.TextField()
	ctrllarvario = models.CharField(max_length=1, choices=SINO, null=True, blank=True)
	fumigacion = models.CharField(max_length=1, choices=SINO, null=True, blank=True)
	educacion = models.CharField(max_length=1, choices=SINO, null=True, blank=True)
	entregatoldillos = models.CharField(max_length=1, choices=SINO, null=True, blank=True)
	cantolperiesgo = models.IntegerField(default=0)
	cantolcoomorb = models.IntegerField(default=0)
	cantoladulmay = models.IntegerField(default=0)
	cantolmencinco = models.IntegerField(default=0)
	cantolembarazadas = models.IntegerField(default=0)

	class Meta:
		verbose_name_plural="Seguimientos Conglomerado Malaria"

	def __str__(self):
		return "{} - {}".format(self.conglomerado - self.hallazgos)

class FileConglomerado(ClaseModelo2):		

mlr/templates/mlr/conglomeradomalaria_form.html
{% extends 'base/basemalaria.html' %}

{% block page_content %}



    {% if obj %}
    <form  method='POST' role='form' action = "{% url 'mlr:conglomeradomlr_edit' obj.pk %}"> 
    {% else %}  
    <form  method='POST' role='form' action = "{% url 'mlr:conglomeradomlr_new' %}">
    {% endif %}
        {% csrf_token %}
              <div class="col-xl-12 col-md-12 mb-12">
                {% if obj %}
                  <div class="card border-left-warning shadow h-100 py-2">
                {% else %}    
                  <div class="card border-left-success shadow h-100 py-2">
                 {%  endif %}   
                    <div class="card-body">
                      <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                          <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                              {% if obj %} Editar {% else %} Nuevo {% endif %} Conglomerado de Malaria
                           </div>                      
                           <div class="dropdown-divider"></div> 
                            <div class="row">
                                  <div class="form-group col-2">
                                      <label for="id_fechainibrote">Fecha Inicio Brote</label>
                                      {{form.fechainibrote}}                               
                                  </div> 
                                  <div class="form-group col-4">
                                      <label for="id_barrio">Barrio/Vereda/Centro Poblado</label>
                                      {{form.barrio}}                               
                                  </div> 
                                  <div class="form-group col-2">
                                      <label for="id_visitado">Visitado</label>
                                      {{form.visitado}}                               
                                  </div> 
                                  <div class="form-group col-2">
                                      <label for="id_fechavisita">F. Visita</label>
                                      {{form.fechavisita}}                               
                                  </div> 
                                  <div class="form-group col-2">
                                      <label for="id_nrodecasos">Nro. Casos</label>
                                      {{form.nrodecasos}}                               
                                  </div> 
                                  
                            </div>
                            <div class="row">
                                 <div class="form-group col-12">
                                    <label for="id_descripcion">Descripción</label>
                                    {{form.descripcion}}                               
                                 </div>
                                
                            </div>
                            <div class="dropdown-divider"></div>
                             <div class="row">
                               <div class="col">
                                 <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>
                                <a class="btn btn-success" href="{% url 'mlr:conglomeradomlr_list' %}">Cancelar</a>                               
                               </div>
                             </div> 
                   </div>
                  </div>  <!-- Cardbody -->
              </div>
            </div>
        {% if obj %} 
            <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2"> 

                          <!-- inicio detalle -->
                            <div class="row" >
                              <div class="col-7" id="prueba">
                                  <div class="row">
                                    <p id="titulo">Casos de Malaria</p> 
                                  </div>
                              <div class="row">
                                  <div class="buttons-toolbar">
                                    <a class="dropdown-item" href="{% url 'mlr:pacconglomlr_new' obj.pk %}"> <span class="fa fa-calendar-plus"></span>Nuevo</a>
                                  </div>

                              <table data-toggle="table"
                                data-pagination="true"
                                data-search="true"
                                data-show-columns="true"
                                data-toolbar=".buttons-toolbar"
                                data-locale="es-MX"
                                data-show-toggle="true"
                                data-show-fullscreen="true">
                              <thead>
                                  <th>Paciente</th>
                                  <th>Fecha Not</th>
                                  <th>Semana</th>
                                  <th>Acción</th>                                  
                              </thead>
                                <tbody>

                                {% for item in cm %}
                                  <tr>
                                    <td>{{item.malaria.paciente }}</td>
                                    <td>{{item.malaria.fec_not|date:"d-m-Y"}}</td>
                                    <td>{{item.malaria.semana}}</td>
                                    <td>
                                    <a class="btn btn-warning btn-circle" href="{% url 'mlr:pacconglomlr_edit' item.pk %}"><i class="far fa-edit"></i></a>
                                    </td>
                                  </tr>
                                  {% endfor %}    
                                 </tbody>                                  
                               </table> 
                                </div>                
                              </div>
                              <div class="col-4" id="prueba">
                                  <div class="row">
                                    <p id="titulo">Documentos Anexos</p> 
                                  </div>
                              <div class="row">
                                  <div class="buttons-toolbar-file">
                                    <a class="dropdown-item" href="{% url 'mlr:fileconglomalaria_new' obj.pk %}"> <span class="fa fa-calendar-plus"></span>Nuevo</a>
                              </div>

                              <table data-toggle="table"
                                data-pagination="true"
                                data-search="true"
                                data-show-columns="true"
                                data-toolbar=".buttons-toolbar-file"
                                data-locale="es-MX"
                                data-show-toggle="true"
                                data-show-fullscreen="true">
                               <thead>
                                  <th>Descripcion</th>                                  
                                  <th>Acción</th>                                  
                                </thead>
                                <tbody>

                                {% for item in fileconglo %}
                                  <tr>                                  
                                  <td><a href="/media/{{item.archivo}} ">{{item.descripcion}}</a></td>                                  
                                  <td>
                                    <a class="btn btn-warning btn-circle" href="{% url 'mlr:fileconglomalaria_edit' item.pk %}"><i class="far fa-edit"></i></a>
                                    </td>
                                  </tr>
                                  {% endfor %}    
                                 </tbody>                                  
                               </table> 
                                </div>                
                              </div> <!-- col-5  -->
                            </div> <!-- Fin de las tablas Seguimiento y de documentos anexos -->
                         
                      </div>
                  </div>  <!-- Cardbody -->
              </div>
            </div>

            <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2"> 

                          
                            <!-- Seguimiento al Conglomerado -->
                            <div class="row" >
                              <div class="col-12" id="prueba">
                                  <div class="row">
                                    <p id="titulo">Seguimientos al Conglomerado - Malaria</p> 
                                  </div>
                              <div class="row">
                                  <div class="buttons-toolbar2">
                                    <a class="dropdown-item" href="{% url 'mlr:segconglomalaria_new' obj.pk %}"> <span class="fa fa-calendar-plus"></span>Nuevo</a>
                                  </div>

                              <table data-toggle="table"
                                data-pagination="true"
                                data-search="true"
                                data-show-columns="true"
                                data-toolbar=".buttons-toolbar2"
                                data-locale="es-MX"
                                data-show-toggle="true"
                                data-show-fullscreen="true">
                               <thead>
                                  <th>Fecha</th>
                                  <th>Hallazgos</th>
                                  <th>C. Larvario</th>
                                  <th>Fumigación</th>
                                  <th>Educación</th>
                                  <th>Entrega Toldillos</th>
                                  <th>Acción</th>                                  
                                </thead>
                                <tbody>

                                {% for item in segconglo %}
                                  <tr>
                                  <td>{{item.fecha|date:"d-m-Y"}}</td>
                                  <td>{{item.hallazgos}}</td>
                                  <td>  {% if item.ctrllarvario == '1' %}
                                          <i class="far fa-thumbs-up text-primary"></i>
                                          {% else %}
                                          <i class="far fa-thumbs-down text-danger"></i>
                                          {% endif %}
                                  </td>

                                        
                                  <td> {% if item.fumigacion == '1' %}
                                          <i class="far fa-thumbs-up text-primary"></i>
                                          {% else %}
                                          <i class="far fa-thumbs-down text-danger"></i>
                                          {% endif %}                                    
                                  </td>
                                  <td> {% if item.educacion == '1' %}
                                          <i class="far fa-thumbs-up text-primary"></i>
                                          {% else %}
                                          <i class="far fa-thumbs-down text-danger"></i>
                                          {% endif %} 
                                    
                                  </td>
                                  <td> {% if item.entregatoldillos == '1' %}
                                          <i class="far fa-thumbs-up text-primary"></i>
                                          {% else %}
                                          <i class="far fa-thumbs-down text-danger"></i>
                                          {% endif %} 
                                  <td>
                                    <a class="btn btn-warning btn-circle" href="{% url 'mlr:segconglomalaria_edit' item.pk %}"><i class="far fa-edit"></i></a>
                                    </td>
                                  </tr>
                                  {% endfor %}    
                                 </tbody>                                  
                               </table> 
                                </div>                
                              </div>
                            </div> <!-- Fin de seguimiento al Conglomerado -->
                           
                           
                        </div>
                      </div>
                    </div>
                  </div>
                  {% endif %} 
                </div>
    </form>


	
{% endblock page_content %}

{% block js_page %}

<script>

$(function(){

  $("#id_fechainibrote, #id_fechavisita").datetimepicker({
    format:'d/m/Y',
    timepicker:false
  });


    $('#id_barrio').select2({
      placeholder: "Seleccione un Barrio",
      allowClear: true
    });

 });

 </script> 
{% endblock js_page %}

mlr/templates/mlr/conglomeradopacmalaria_form.html
{% extends 'base/basemalaria.html' %}

{% block page_content %}


<div class="modal-dialog modal-lg">
  <div class="modal-content">
    {% if obj %}
    <form  method='POST' role='form' action = "{% url 'mlr:pacconglomlr_edit' obj.pk %}"> 
    {% else %}  
    <form  method='POST' role='form' action = "{% url 'mlr:pacconglomlr_new' idconglomerado %}">
    {% endif %}
        {% csrf_token %}
              <div class="col-xl-12 col-md-12 mb-12">
                {% if obj %}
                  <div class="card border-left-warning shadow h-100 py-2">
                {% else %}    
                  <div class="card border-left-success shadow h-100 py-2">
                 {%  endif %}   
                    <div class="card-body">
                      <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                          <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                              {% if obj %} Editar {% else %} Nuevo {% endif %} Paciente de conglomerado
                           </div>                      
                           <div class="dropdown-divider"></div> 
            
                            <div class="row">
                               <div class="form-group col-12">
                                  <input type="hidden" name="conglomerado" value="{{idconglomerado}}">
                                  <label for="">{{conglo}}</label>
                               </div>
                            </div>
                            <div class="row">
                                  <div class="form-group col-12">
                                        <label for="id_malaria">Paciente de malaria</label>
                                       {{form.malaria}}                               
                                  </div>                                    
                            </div>                                 
                           <div class="dropdown-divider"></div>
                             <div class="row">
                               <div class="col">
                                 <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>
                                <a class="btn btn-success" href="{% url 'mlr:conglomeradomlr_edit' idconglomerado %}">Cancelar</a>
                               
                               </div>
                             </div> 
                           </div>                
                      </div>
                    </div>
                </div>
              </div>
    </form>
  </div>
</div>

	
{% endblock page_content %}

{% block js_page %}

<script>

$(function(){

   $('#id_malaria').select2({
      placeholder: "Seleccione el Paciente",
      allowClear: true
    });

    $('#id_municipio').chained("#id_departamento");
    
 });

 </script> 
{% endblock js_page %}