bai/urls.py
from django.urls import path
from .views import importCie10, DiagnosticoList, importRips, Grafdiagnosticoscie10, Home, \
DiagnosticoUpdate, DiagnosticoCreate, Archivocontrolist, Archivoconsultalist, ListadoDiagnostico, \
georrefenciarDiagCE, geolocMapaCalorDiagCE, mapaCalarDiagCE, listarRipsCargados

app_name='bai'


urlpatterns = [
	path('', Home.as_view(), name='home'),
	path('importcie10', importCie10, name='Import_cie10'),
	path('rips', importRips, name='importar_rips'),
	path('cie10/estcoom', Grafdiagnosticoscie10.as_view(), name='estadistica_cie10'),
	path('cie10', DiagnosticoList.as_view(), name='cie10list'),
	path('cie10/edit/<int:pk>', DiagnosticoUpdate.as_view(), name='cie10_edit'),
	path('cie10/new', DiagnosticoCreate.as_view(), name='cie10_new'),
	path('rips/ctrl', Archivocontrolist.as_view(), name='rips_control'),
	path('rips/listar/<int:id>', listarRipsCargados, name='rips_listar'),
	path('rips/ce', Archivoconsultalist.as_view(), name='rips_consulta'),
	path('rips/grce', ListadoDiagnostico.as_view(), name='georref_ce'),
	path('rips/grce/<int:iddiag>', georrefenciarDiagCE, name='georref_ce_map'),
	path('rips/grmcce/<int:iddiag>', geolocMapaCalorDiagCE, name='georref_mapcalor_ce'),
	path('rips/mapacalorce/<int:iddiag>', mapaCalarDiagCE, name='mapcalor_ce'),





]

den/urls.py
from django.contrib import admin
from django.urls import path


from .views import importarDengue210, dengueList, dengueEdit, SegPacDengueCreate, SegPacDengueEdit, \
inactivar_ficha_dengue, dengueGraveList, dengueMortalidadList, GrafDenguemes, FileDengueUpdate, \
FileDengueCreate, IecDengueCreate, IecDengueUpdate, ContactoIecDengueCreate, ContactoIecDengueUpdate, \
geolocDengue210, GrafDengueSemEpi, EstDengueSemEpi, Home, geolocDengue220, mapaCalarDengueGrave

app_name='den'   

urlpatterns = [
	path('', Home.as_view(), name='home'),
	path('dengue210/', importarDengue210, name='importar_dengue_210'),
	# path('dengue/', DengueList.as_view(), name='dengue_list'),
	path('dengue/210/', dengueList, name='dengue_list'),
	path('dengue/220/', dengueGraveList, name='dengue_grave_list'),
	path('dengue/580/', dengueMortalidadList, name='dengue_mortalidad_list'),
	path('dengue/del/<int:id>', inactivar_ficha_dengue, name='dengue_inact'),	 
	path('dengue/edit/<int:iddengue>', dengueEdit, name='dengue_edit'),
	path('dengue/render/<int:iddengue>', SegPacDengueCreate.as_view(), name='render_segpac_dengue'),
	path('dengue/segedit/<int:pk>',SegPacDengueEdit.as_view(), name='segpac_dengue_edit'),
	path('dengue/filedengue/new/<int:iddengue>', FileDengueCreate.as_view(), name='filedengue_new'),
	path('dengue/filedengue/edit/<int:pk>', FileDengueUpdate.as_view(), name='filedengue_edit'),
	path('dengue/iec/new/<int:iddengue>', IecDengueCreate.as_view(), name='iecdengue_new'),
	path('dengue/iec/edit/<int:pk>', IecDengueUpdate.as_view(), name='iecdengue_edit'),
    path('dengue/iec/contact/new/<int:idiecdengue>', ContactoIecDengueCreate.as_view(), name='contactiecdengue_new'),
	path('dengue/iec/contact/edit/<int:pk>', ContactoIecDengueUpdate.as_view(), name='contactiecdengue_edit'),
	path('dengue/estmes', GrafDenguemes.as_view(), name='est_dengue_mes'),
	path('dengue/est/selanioepi', EstDengueSemEpi.as_view(), name='est_dengue_selanioepi'),	 
	path('dengue/est/semepiu', GrafDengueSemEpi.as_view(), name='est_dengue_semepi'),
	path('dengue/geoloc210', geolocDengue210, name='geoloc_evento_210'),
	path('dengue/geoloc220', geolocDengue220, name='geoloc_evento_220'),
	path('dengue/mapcal220', mapaCalarDengueGrave, name='mapa_calor_220'),

	

	 
	 #path('dengue/new/<int:iddengue>', SegPacDengueCreate.as_view(), name='segpac_dengue_new'),

] 

suisa/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('cnf.urls', namespace='config')),
    path('sint/', include('sint.urls', namespace='sint')),
    path('den/', include('den.urls', namespace='den')),    
    path('cvd/', include('cvd.urls', namespace='cvd')),
    path('bai/', include('bai.urls', namespace='bai')), #Rips
    path('lab/', include('lab.urls', namespace='lab')),
    path('mlr/', include('mlr.urls', namespace='mlr')),
    path('sam/', include('sam.urls', namespace='sam')),    
    path('pai/', include('pai.urls', namespace='pai')),    
    path('aseg/', include('aseg.urls', namespace='aseg')),
    path('pqrs/', include('pqrs.urls', namespace='pqrs')),
    path('ruaf/', include('ruaf.urls', namespace='ruaf')),    
    path('seguridad/', include('seguridad.urls', namespace='seguridad')),    
    path('res4505/', include('res4505.urls', namespace='res4505')), 
    path('admin/', admin.site.urls),

    

] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

bai/models.py
from django.db import models
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver

from cnf.models import ClaseModelo2, Ips, Paciente, UmEdad, Eps, Tipodoc, Regimen, Sexo, Departamento, \
Municipio, Area

# Create your models here.

class AmbitoProcedimiento(ClaseModelo2):
	codigo=models.IntegerField(unique=True)
	descripcion = models.CharField(max_length=50)

	class Meta:
		verbose_name='Ambito de procedimientos'
		ordering = ['descripcion']

	def __str__(self):
		return "{}".format(self.descripcion)

class Cups(ClaseModelo2):
	codigo = models.CharField(max_length=10, unique=True)
	descripcion = models.CharField(max_length=300)

	class Meta:
		verbose_name = 'Código Cups'
		verbose_name_plural = 'Códigos Cups'
		ordering = ['descripcion']

	def __str__(self):
		return "{}:{}".format(self.codigo, self.descripcion)

class Cums(ClaseModelo2):
	SINO = (
        ('SI', 'Si'),
        ('NO', 'No'),
    )
	ESTADO = (
        ('Activo', 'Activo'),
        ('Inactivo', 'Inactivo'),
    )
	expediente = models.IntegerField(null=True, blank=True)
	producto = models.CharField(max_length=200, null=True, blank=True)
	titular = models.CharField(max_length=200, null=True, blank=True)
	regsanitario = models.CharField(max_length=150, null=True, blank=True)
	fechaexpedicion = models.DateField(null=True, blank =True)
	fechavencimiento = models.DateField(null=True, blank =True)
	estadoregistro = models.CharField(max_length=100, null=True, blank =True)
	expedientecum = models.CharField(max_length=20, null=True, blank =True)
	consecutivocum = models.IntegerField(null=True, blank=True)
	cantidadcum = models.CharField(max_length=20, blank=True, null=True)
	descripcioncomercial = models.CharField(max_length=300)
	estado = models.CharField(max_length=10, choices=ESTADO, null=True, blank=True, default='Activo')
	fechaactivo = models.DateField(null=True, blank=True)
	fechainactivo = models.DateField(null=True, blank=True)
	muestramedica = models.CharField(max_length=2, choices=SINO, null=True, blank=True, default='NO')
	unidad = models.CharField(max_length=10, null=True, blank=True)
	atc = models.CharField(max_length=20, null=True, blank=True)
	descripcionatc = models.CharField(max_length=300, null=True, blank=True)
	viaadministracion = models.CharField(max_length=80, null=True, blank=True)
	concentracion = models.CharField(max_length=10, null=True, blank=True)
	principioactivo = models.CharField(max_length=300, null=True, blank=True)
	unidadmedida = models.CharField(max_length=50, null=True, blank=True)
	cantidad = models.CharField(max_length=20,null=True, blank=True)
	unidadreferencia = models.CharField(max_length=100,null=True, blank=True)
	formafarmaceutica = models.CharField(max_length=100,null=True, blank=True)
	nombrerol = models.CharField(max_length=100,null=True, blank=True)
	tiporol = models.CharField(max_length=50, null=True, blank=True)
	modalidad = models.CharField(max_length=50, null=True, blank=True)


	class Meta:
		verbose_name = 'Medicamento'
		verbose_name_plural = 'Listado de Medicamentos'
		ordering = ['descripcioncomercial']

	def __str__(self):
		return "{}:{}".format(self.codigo, self.descripcioncomercial)

class FinalidadProcedimiento(ClaseModelo2):
	codigo = models.IntegerField()
	descripcion = models.CharField(max_length=80)

	class Meta:
		verbose_name='Finalidad del procedimientos'
		ordering = ['descripcion']

	def __str__(self):
		return "{}".format(self.descripcion)

class ImportarCie10(ClaseModelo2):
	file_name = models.FileField(upload_to='bai', null=True, blank=True)
	file_cups=models.FileField(upload_to='bai',null=True, blank=True)
	file_cums=models.FileField(upload_to='bai',null=True, blank=True)
	uploaded =models.DateField(auto_now_add=True)
	activated= models.BooleanField(default=False)

	def __str__(self):
		return f"Id del Archivo {self.id}"

class Finalidad(ClaseModelo2):
	codigo = models.CharField(max_length=2)
	descripcion = models.CharField(max_length=80)

	def __str__(self):
		return "{}".format(self.descripcion)

	class Meta:
		verbose_name_plural="Finalidad de consulta"
		ordering=['descripcion']

class CausaExterna(ClaseModelo2):
	codigo = models.CharField(max_length=2)
	descripcion = models.CharField(max_length=80)

	def __str__(self):
		return "{}".format(self.descripcion)

	class Meta:
		verbose_name_plural="Causa Externa"
		ordering=['descripcion']	

class Diagnosticos(ClaseModelo2):
	SINO = (
        ('SI', 'Si'),
        ('NO', 'No'),
    )
	codigo=models.CharField(max_length=16)
	descripcion = models.CharField(max_length=300)
	notifobligatoria = models.CharField(max_length=2, choices=SINO, null=True, blank=True, default='NO')
	idcapitulo = models.IntegerField()
	capitulo = models.CharField(max_length=300)
	codcie3=models.CharField(max_length=3)
	descripcie3= models.CharField(max_length=300)

	def __str__(self):
		return "{} - {}".format(self.codigo, self.descripcion)

	class Meta:
		verbose_name_plural="Diagnosticos"
		ordering=['descripcion']	


class DestinoSalida(ClaseModelo2):
	codigo=models.IntegerField(unique=True)	
	descripcion = models.CharField(max_length=80)

	class Meta:
		verbose_name='Desntino a la salida'
		ordering = ['descripcion']

	def __str__(self):
		return "{}".format(self.descripcion)

class EstadoSalida(ClaseModelo2):
	codigo=models.IntegerField(unique=True)	
	descripcion = models.CharField(max_length=50)

	class Meta:
		verbose_name='Estado a la salida'
		ordering = ['descripcion']

	def __str__(self):
		return "{}".format(self.descripcion)

class FormaRealizactoQx(ClaseModelo2):
	codigo=models.IntegerField(unique=True)
	descripcion = models.CharField(max_length=100)

	class Meta:
		verbose_name='Forma de realización acto Quirurgico'
		ordering = ['descripcion']

	def __str__(self):
		return "{}".format(self.descripcion)

class PersonalAsistencial(ClaseModelo2):
	codigo=models.IntegerField(unique=True)	
	descripcion = models.CharField(max_length=80)

	class Meta:
		verbose_name='Personal Asistencial'
		ordering = ['descripcion']

	def __str__(self):
		return "{}".format(self.descripcion)

class PeriodoImportRips(ClaseModelo2):
	ips = models.ForeignKey(Ips, on_delete=models.CASCADE)
	fecharemision= models.DateField()
	fileCT = models.FileField(upload_to='bai')
	fileAF = models.FileField(upload_to='bai')
	fileAU = models.FileField(upload_to='bai', null=True, blank=True)
	fileUS = models.FileField(upload_to='bai')
	fileAH = models.FileField(upload_to='bai', null=True, blank=True)
	fileAT = models.FileField(upload_to='bai', null=True, blank=True)
	fileAC = models.FileField(upload_to='bai', null=True, blank=True)
	fileAP = models.FileField(upload_to='bai', null=True, blank=True)
	fileAM = models.FileField(upload_to='bai', null=True, blank=True)
	fileAN = models.FileField(upload_to='bai', null=True, blank=True)
	activated = models.BooleanField(default=False)

	class Meta:
		verbose_name='Periodo a Importar Rips'
		ordering = ['-fecharemision']

	def __str__(self):
		return "{} - {}".format(self.ips, self.fecharemision)



class TipoMedicamento(ClaseModelo2):
	codigo=models.IntegerField(unique=True)	
	descripcion = models.CharField(max_length=50)

	class Meta:
		verbose_name='Tipo de Medicamento'
		ordering = ['descripcion']

	def __str__(self):
		return "{}".format(self.descripcion)

class TipoServicio(ClaseModelo2):
	codigo = models.CharField(max_length=1, unique=True)
	descripcion = models.CharField(max_length=50)

	class Meta:
		verbose_name='Tipo de Servicio'
		ordering = ['descripcion']

	def __str__(self):
		return "{}".format(self.descripcion)

class TipoDiagPrincipal(ClaseModelo2):
	codigo = models.IntegerField()
	descripcion = models.CharField(max_length=50)

	class Meta:
		verbose_name='Tipo de Diagnóstico Principal'
		ordering=['descripcion']

	def __str__(self):
		return "{}".format(self.descripcion)


class ViaIngreso(ClaseModelo2):
	codigo=models.IntegerField(unique=True)
	descripcion = models.CharField(max_length=50)

	class Meta:
		verbose_name='Vía de Ingreso a la Institución'
		ordering = ['descripcion']

	def __str__(self):
		return "{}".format(self.descripcion)

class RipsControl(ClaseModelo2):
	ips = models.ForeignKey(Ips, on_delete=models.CASCADE)
	fecharemision = models.DateField()
	codarchivo = models.CharField(max_length=10)
	totalreg = models.IntegerField()
	periodoimportRips = models.ForeignKey(PeriodoImportRips, on_delete= models.CASCADE, null=True, blank=True)

	def __str__(self):
		return "{} - {}".format(self.ips, self.fecharemision)

	class Meta:
		verbose_name_plural = 'Rips de control'

class Tipousuario(ClaseModelo2):
	codigo=models.IntegerField()
	descripcion=models.CharField(max_length=100)
	regimen = models.ForeignKey(Regimen, on_delete=models.CASCADE, null=True, blank=True)

	class Meta:
		verbose_name="Tipo de usuario"
		ordering = ['descripcion']

	def __str__(self):
		return "{}".format(self.descripcion)

class RipsUsuarios(ClaseModelo2):
	tipodoc = models.ForeignKey(Tipodoc, on_delete=models.CASCADE)
	identificacion = models.CharField(max_length=20)
	eps = models.ForeignKey(Eps, on_delete=models.CASCADE, null=True, blank=True)
	tipousuario = models.ForeignKey(Tipousuario, on_delete=models.CASCADE, null=True, blank=True)
	apellido1 = models.CharField(max_length=60)
	apellido2 = models.CharField(max_length=60, null=True, blank=True)
	nombre1 = models.CharField(max_length=60)
	nombre2 = models.CharField(max_length=60, null=True, blank=True)
	edad = models.IntegerField(default=0, null=True, blank=True)
	umedad = models.ForeignKey(UmEdad, on_delete=models.CASCADE, null=True, blank=True)
	sexo = models.ForeignKey(Sexo,on_delete=models.CASCADE, null=True, blank=True)
	departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE, null= True, blank = True)
	municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE, null= True, blank = True)
	area = models.ForeignKey(Area, on_delete=models.CASCADE, null= True, blank = True)

bai/forms.py
from django import forms
from .models import ImportarCie10, PeriodoImportRips, Diagnosticos

class PeriodoImportRipsForm(forms.ModelForm):
	
	class Meta:
		model= PeriodoImportRips
		fields=['ips','fecharemision','fileCT','fileUS','fileAC','fileAP','fileAU', \
		 'fileAH', 'fileAM', 'fileAF', 'fileAT']
		exclude=['activated','um','uc','fm','fc']

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs) #para que se inicialice
		for field in iter(self.fields):
			self.fields[field].widget.attrs.update({				
				'class':"form-control" #colocar la clase de bootsTrap a todos los controles o campos
			})
		self.fields['fecharemision'].widget.attrs['readonly'] = True


class ImportCie10Form(forms.ModelForm):
	class Meta:
		model=ImportarCie10
		fields=['file_name','file_cups', 'file_cums']
		exclude=['uploaded','activated','um','uc','fm','fc']
		
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs) #para que se inicialice
		for field in iter(self.fields):
			self.fields[field].widget.attrs.update({				
				'class':"form-control" #colocar la clase de bootsTrap a todos los controles o campos
			})


class DiagnosticosForm(forms.ModelForm):
	class Meta:
		model = Diagnosticos
		exclude = ['uploaded','activated','um','uc','fm','fc']
		fields=['codigo','descripcion','notifobligatoria','idcapitulo', 'capitulo','codcie3','descripcie3']

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs) #para que se inicialice
		for field in iter(self.fields):
			self.fields[field].widget.attrs.update({				
				'class':"form-control" #colocar la clase de bootsTrap a todos los controles o campos
			})

		

bai/templates/bai/diagnostico_form.html
{% extends 'base/baserips.html' %}

{% block page_content %}

<div class="modal-dialog modal-lg">
  <div class="modal-content">
 {% if obj %}
  <form  method='POST' role='form' action = "{% url 'bai:cie10_edit' obj.pk %}"> 
    {% else %}  
    <form  method='POST' role='form' action = "{% url 'bai:cie10_new' %}">
    {% endif %}
        {% csrf_token %}

          <div class="col-xl-12 col-md-12 mb-12">
            <div class="card border-left-success shadow h-100 py-2">
                 <div class="card-body">
                      <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                          <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                              Registro de Diagnosticos:                              
                           </div>                      
                           <div class="dropdown-divider"></div> 
                           <div class="row">
                               <div class="form-group col-2">
                                      <label for="id_idcapitulo">Id Capitulo</label>
                                      {{form.idcapitulo}}                             
                                  </div>
                                  <div class="form-group col-10">
                                        <label for="id_capitulo">Capitulo</label>
                                        <br>
                                        {{form.capitulo}}                               
                                  </div>
                           </div>
                            <div class="row">
                                 <div class="form-group col-2">
                                      <label for="id_codcie3">Id Grupo</label>
                                      {{form.codcie3}}                             
                                  </div>
                                  <div class="form-group col-10">
                                        <label for="id_descripcie3">Descripción grupo</label>
                                        <br>
                                        {{form.descripcie3}}                               
                                  </div>
                            </div>
                            <div class="row">
                              
                            </div>
                            <div class="row">
                                 <div class="form-group col-2">
                                      <label for="id_codigo">Código CIE10</label>
                                      {{form.codigo}}                             
                                  </div>
                                  <div class="form-group col-10">
                                        <label for="id_descripcion">Descripción</label>
                                        <br>
                                        {{form.descripcion}}                               
                                  </div>
                                                               
                            </div>
                            <div class="row">
                                  <div class="form-group col-6">
                                      <label for="id_notifobligatoria">Notificación obligatoria</label>
                                      {{form.notifobligatoria}}                             
                                  </div> 
                            </div>

                           <div class="dropdown-divider"></div>
                             <div class="row">
                               <div class="col">
                                 <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>

                                 <a class="btn btn-success" href="{% url 'bai:cie10list' %}">Cancelar</a>
                              
                               </div>
                             </div> 
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
  </form>
  </div>
</div>
	
{% endblock page_content %}

{% block js_page %}
<script>


$(function(){  
  $("#id_fechamuestra, #id_fechaposexpo, #id_fechainisintomas").datetimepicker({
    format:'d/m/Y',
    timepicker:false
  });


    $('#id_paciente').select2({
      placeholder: "Seleccione un Paciente",
      allowClear: true
    });


});

  
  </script>

  {% endblock js_page%}

bai/templates/bai/diagnostico_list.html
{% extends 'base/baserips.html' %}
{% block page_content %}
	  <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Listado de Diagnósticos</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">Acciones:</div>
                      <a class="dropdown-item" href="{% url 'bai:cie10_new' %} "> <span class="fa fa-calendar-plus"></span>Nuevo</a>
                      
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                  {% if not obj  %}
                        No hay Diagnósticos CIE-10
                  {% endif %}

                  <div class="buttons-toolbar">
                    <a class="dropdown-item" href="{% url 'bai:cie10_new' %} "> <span class="fa fa-calendar-plus"></span>Nuevo</a>
                  </div>


                  <table data-toggle="table"
                    data-pagination="true"
                    data-search="true"
                    data-show-columns="true"
                    data-toolbar=".buttons-toolbar"
                    data-locale="es-MX"
                    data-show-toggle="true"
                    data-show-fullscreen="true"

                  >
                    <thead>   
                      <th data-field='codigo' data-sortable="true">Código</th> 
                      <th data-field='descripcion' data-sortable="true">Descripción</th>
                      <th class="all">Acciones</th> 
                    </thead>  
                    <tbody>
                      {% for item in obj %}
                        <tr>
                            <td>{{item.codigo}}</td>
                            <td>{{item.descripcion}}</td>                            
                            <td>

                            <a class="btn btn-warning btn-circle" href="{% url 'bai:cie10_edit' item.id %}"><i class="far fa-edit"></i></a>  

                            <a href="{% url 'den:dengue_inact' item.id %}"><i class="far fa-thumbs-down"></i></a> 
                            </td>
                          </tr>                   
                      {% endfor %}
                    </tbody>

                  </table>
                </div>
            </div>
{% endblock page_content %}

{% block js_page %}
 <script>
  
 </script>

 {% endblock %}

bai/templates/bai/importRips.html
{% extends 'base/baserips.html' %}
	
{% block page_content %}
<div class="card-body">
<h1> Importar Rips </h1>
<form action="" method="POST" role='form' enctype="multipart/form-data">
    {% csrf_token %} 
		<div class="dropdown-divider"></div> 
		<div class="row" id="prueba">
    
        	<div class="form-group col-3">
	           <label for="id_ips">Ips</label>              
            	 {{ form.ips }} 
	        </div>	        
	        <div class="form-group col-2">
	           <label for="id_fecharemision">Fecha de Remisión</label>              
              {{ form.fecharemision }} 
	        </div>	        
        </div>
        
        <div class="row">
	        <div class="form-group col-6">
	           <label for="id_fileCT">Rips de control</label>              
              {{ form.fileCT }} 
	        </div>	        
        
        	<div class="form-group col-6">
	           <label for="id_fileUS">Rips de Usuarios</label>              
              {{ form.fileUS }} 
	        </div>	        
        </div>
        <div class="row">
        	<div class="form-group col-6">
	           <label for="id_fileAC">Rips de Consultas</label>              
              {{ form.fileAC }} 
	        </div>	        
       
        	<div class="form-group col-6">
	           <label for="id_fileAP">Rips de Procedimientos</label>              
              {{ form.fileAP }} 
	        </div>	        
        </div>
        <div class="row">
        	<div class="form-group col-6">
	           <label for="id_fileAU">Rips de Urgencia</label>              
              {{ form.fileAU }} 
	        </div>	 
	        <div class="form-group col-6">
	           <label for="id_fileAH">Rips de Hospitalización</label>              
              {{ form.fileAH }} 
	        </div>	       
        </div>     
        <div class="row">
        	<div class="form-group col-6">
	           <label for="id_fileAM">Rips de Medicamento</label>              
              {{ form.fileAM }} 
	        </div>	  
	        <div class="form-group col-6">
	           <label for="id_fileAF">Rips de Transacciones</label>              
              {{ form.fileAF }} 
	        </div>      
        </div>      
        <div class="row">
        	<div class="form-group col-6">
	           <label for="id_fileAT">Rips de Otros servicios</label>              
              {{ form.fileAT }} 
	        </div>	  
	        
        </div> 
        
        <div class="row">
        	<div class="form-group col-8">
        	<button type="submit" class="btn btn-primary">Importar</button>
        </div>
        </div>
</form>
</div>	
{% endblock page_content %}

{% block js_page %}
<script>
	$('.custom-file-input').on('change', function(event) {
	    var inputFile = event.currentTarget;
	    $(inputFile).parent()
	        .find('.custom-file-label')
	        .html(inputFile.files[0].name);
	}); 


$(function(){  
  $("#id_fecharemision").datetimepicker({
    format:'d/m/Y',
    timepicker:false
  });


});


</script>
{% endblock %}